### ISSUE TITLE
Post Removal Reqeust - UW Homework Solution

### ISSUE THREAD

**Issue by jsanders89** [kkoprow/Java#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington. The following post in this repository contains a solution to a homework assignment that is the same as our own, the cumulative song about an old woman who swallowed a fly:

https://github.com/kkoprow/Java/blob/master/Song.java

This post's solution code is indexed by Google, enabling our current students to easily find it and cheat on their assignments.

Would you please remove this post or make it private in order to help us enforce our academic policy?

By removing the post, you would be removing a tool that our students could use in academic misconduct.

Thank you,
Jonathan Sanders
Intro Support, Computer Science & Engineering
University of Washington
jsanders@cs.washington.edu

More info on our course: http://courses.cs.washington.edu/courses/cse142/15su/

**Comment by kkoprow** [comment]
I apologize for the delay.

I have removed this solution.

If any more of these assignments interfere with your instruction please email me.
